# Generated by Django 3.2.4 on 2021-07-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloghome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='myblogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('author', models.CharField(default='', max_length=30)),
                ('slug', models.CharField(default='', max_length=25)),
                ('tags', models.CharField(default='', max_length=50)),
                ('contant', models.TextField(default='')),
                ('timestapm', models.DateTimeField(blank=True, default='2020-05-03 4:45')),
            ],
        ),
        migrations.AddField(
            model_name='myusers',
            name='userName',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='Email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
    ]
